name: Lighthouse CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Wait for GitHub Pages deployment
        if: github.event_name == 'push'
        run: sleep 60
        
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://edgafner.github.io
            https://edgafner.github.io/azdlib.html
            https://edgafner.github.io/gbrowserlib.html
          uploadArtifacts: true
          temporaryPublicStorage: true
          
      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const results = require('./lighthouse-results.json');
            const comment = `### Lighthouse Performance Results
            
            | Page | Performance | Accessibility | Best Practices | SEO |
            |------|------------|---------------|----------------|-----|
            ${results.map(r => `| ${r.url} | ${r.performance} | ${r.accessibility} | ${r.bestPractices} | ${r.seo} |`).join('\n')}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });